/**
 * Idea Stage Content — Early brainstorming concepts
 * These are lightweight ideas in the "idea" stage, not yet developed into full concepts
 */
import type { ContentItem } from "./types";

export const IDEA_STAGE_CONTENT: ContentItem[] = [
  // ─── Yoga Practice Ideas ───
  {
    id: "idea1",
    stage: "idea",
    status: "draft",
    title: "Chair Yoga Series for Office Workers",
    description: "5-part series showing simple yoga stretches that can be done at a desk or with a chair. Target professionals who sit all day.",
    pillarIds: ["p1", "p2"],
    segmentIds: ["s1", "s2"],
    createdAt: "2026-02-28T09:00:00",
    updatedAt: "2026-02-28T09:00:00",
  },
  {
    id: "idea2",
    stage: "idea",
    status: "draft",
    title: "Yoga Poses for Better Sleep",
    description: "Evening wind-down routine with gentle poses that promote relaxation and better sleep quality.",
    pillarIds: ["p1", "p5"],
    segmentIds: ["s3", "s5"],
    createdAt: "2026-02-27T14:00:00",
    updatedAt: "2026-02-27T14:00:00",
  },
  {
    id: "idea3",
    stage: "idea",
    status: "draft",
    title: "Breathwork 101: 3 Techniques for Stress Relief",
    description: "Simple breathwork tutorial showing three foundational breathing techniques for managing daily stress and anxiety.",
    pillarIds: ["p1", "p5"],
    segmentIds: ["s3", "s5"],
    createdAt: "2026-02-28T11:00:00",
    updatedAt: "2026-02-28T11:00:00",
  },

  // ─── Fitness & Movement Ideas ───
  {
    id: "idea4",
    stage: "idea",
    status: "draft",
    title: "10-Minute Walking Workout Challenge",
    description: "Low-impact walking workout series perfect for beginners. Could be a 7-day challenge format.",
    pillarIds: ["p2"],
    segmentIds: ["s4", "s1"],
    createdAt: "2026-02-27T10:00:00",
    updatedAt: "2026-02-27T10:00:00",
  },
  {
    id: "idea5",
    stage: "idea",
    status: "draft",
    title: "Strength Training Myths for Women Over 40",
    description: "Educational content debunking common strength training myths that hold women back from resistance training.",
    pillarIds: ["p2"],
    segmentIds: ["s1", "s2"],
    createdAt: "2026-02-28T08:00:00",
    updatedAt: "2026-02-28T08:00:00",
  },
  {
    id: "idea6",
    stage: "idea",
    status: "draft",
    title: "Foam Rolling Tutorial: Release Tight Hips",
    description: "Step-by-step foam rolling routine targeting hip flexors and IT band for improved mobility.",
    pillarIds: ["p2"],
    segmentIds: ["s1", "s3"],
    createdAt: "2026-02-26T15:00:00",
    updatedAt: "2026-02-26T15:00:00",
  },

  // ─── Nutrition & Wellness Ideas ───
  {
    id: "idea7",
    stage: "idea",
    status: "draft",
    title: "Anti-Inflammatory Breakfast Bowl Recipes",
    description: "Quick, colorful breakfast bowl recipes featuring anti-inflammatory ingredients. Visual recipe cards.",
    pillarIds: ["p3"],
    segmentIds: ["s5", "s1"],
    createdAt: "2026-02-27T13:00:00",
    updatedAt: "2026-02-27T13:00:00",
  },
  {
    id: "idea8",
    stage: "idea",
    status: "draft",
    title: "Protein Myths: How Much Do You Actually Need?",
    description: "Educational content addressing protein intake confusion for active women 40+.",
    pillarIds: ["p3"],
    segmentIds: ["s1", "s2", "s5"],
    createdAt: "2026-02-28T07:00:00",
    updatedAt: "2026-02-28T07:00:00",
  },
  {
    id: "idea9",
    stage: "idea",
    status: "draft",
    title: "Gut Health 101: Foods That Support Digestion",
    description: "Beginner-friendly guide to gut-healthy foods with simple swaps and additions to daily meals.",
    pillarIds: ["p3"],
    segmentIds: ["s5"],
    createdAt: "2026-02-27T16:00:00",
    updatedAt: "2026-02-27T16:00:00",
  },

  // ─── Community Building Ideas ───
  {
    id: "idea10",
    stage: "idea",
    status: "draft",
    title: "Member Spotlight: Sarah's Yoga Journey",
    description: "Feature story highlighting a community member's transformation and yoga practice evolution.",
    pillarIds: ["p4"],
    segmentIds: ["s3"],
    createdAt: "2026-02-28T10:00:00",
    updatedAt: "2026-02-28T10:00:00",
  },
  {
    id: "idea11",
    stage: "idea",
    status: "draft",
    title: "Monthly Wellness Challenge Announcement",
    description: "Announce March wellness challenge with prizes and community accountability features.",
    pillarIds: ["p4"],
    segmentIds: ["s1", "s2", "s3", "s4", "s5"],
    createdAt: "2026-02-26T12:00:00",
    updatedAt: "2026-02-26T12:00:00",
  },

  // ─── Mindful Living Ideas ───
  {
    id: "idea12",
    stage: "idea",
    status: "draft",
    title: "5-Minute Morning Meditation for Beginners",
    description: "Guided audio meditation for women new to mindfulness practice. Calming, accessible.",
    pillarIds: ["p5"],
    segmentIds: ["s4", "s5"],
    createdAt: "2026-02-27T08:00:00",
    updatedAt: "2026-02-27T08:00:00",
  },
  {
    id: "idea13",
    stage: "idea",
    status: "draft",
    title: "Creating a Self-Care Ritual You'll Actually Keep",
    description: "Practical tips for building sustainable self-care habits without overwhelming your schedule.",
    pillarIds: ["p5"],
    segmentIds: ["s1", "s2"],
    createdAt: "2026-02-28T12:00:00",
    updatedAt: "2026-02-28T12:00:00",
  },
  {
    id: "idea14",
    stage: "idea",
    status: "draft",
    title: "Digital Detox: 24-Hour Phone Break Challenge",
    description: "Encourage a 24-hour break from phones/screens with alternative wellness activities suggested.",
    pillarIds: ["p5"],
    segmentIds: ["s3", "s5"],
    createdAt: "2026-02-27T11:00:00",
    updatedAt: "2026-02-27T11:00:00",
  },

  // ─── Mixed Format Ideas ───
  {
    id: "idea15",
    stage: "idea",
    status: "draft",
    title: "Weekly Wellness Tips Carousel Series",
    description: "Ongoing Instagram carousel series with quick wellness tips, facts, and motivation.",
    pillarIds: ["p2", "p3", "p5"],
    segmentIds: ["s1", "s2", "s3", "s4", "s5"],
    createdAt: "2026-02-26T14:00:00",
    updatedAt: "2026-02-26T14:00:00",
  },
];
