/**
 * Yoga / Wellness / Fitness / Nutrition — 12 Example Content Items
 * Distributed across pipeline columns for realistic demo data.
 */
import type { ContentItem } from "./types";

export const WELLNESS_CONTENT: ContentItem[] = [
  // ─── Job 1: Instagram Reels — Morning Mobility Flow ─── IN PRODUCTION (step: assets)
  {
    id: "w1",
    stage: "concept",
    status: "in-progress",
    title: "60-sec Morning Mobility Flow (No equipment)",
    description: "Quick morning mobility routine targeting stiff joints and tight muscles. Designed for beginners who want a fast, equipment-free flow to start their day with better range of motion.",
    pillarIds: ["p2"],
    segmentIds: ["s4"],
    createdAt: "2026-02-20T07:00:00",
    updatedAt: "2026-02-26T14:00:00",
    hook: "Your body shouldn't feel 80 when you're 30. Try this 60-second morning reset.",
    objective: "engagement",
    owner: "Brett Lewis",
    platform: "instagram",
    contentType: "reel",
    keyMessage: "A 60-second flow can transform your mornings",
    cta: { type: "other", text: "Follow for daily flows" },
    claimsFlag: false,
    production: {
      productionStep: "assets",
      brief: {
        strategy: { objective: "awareness", audienceSegmentIds: ["s4"], pillarIds: ["p2"], keyMessage: "A 60-second flow can transform your mornings", ctaType: "follow", ctaText: "Follow for daily flows", tonePreset: "casual" },
        platformRules: { durationTarget: 60, hookType: "outcome-first" },
        creativePlan: { musicNotes: "Lo-fi ambient beat, calm energy" },
        compliance: { containsClaims: false, disclosureNeeded: false },
        approved: true, approvedAt: "2026-02-22T10:00:00", approvedBy: "Brand Reviewer",
      },
      sources: [],
      outputs: {
        scriptVersions: [{ id: "sv-w1", content: "0:00-0:03 Hook: Your body shouldn't feel 80.\n0:03-0:15 Cat-Cow stretch (3 reps)\n0:15-0:30 Thoracic rotation (each side)\n0:30-0:45 Hip circles (each direction)\n0:45-0:55 Standing reach + fold\n0:55-1:00 CTA: Follow for daily flows", version: 1, approved: true }],
        hookVariants: ["Your body shouldn't feel 80 when you're 30", "This 60-second routine changed my mornings", "No gym, no equipment, just movement", "Try this before your coffee tomorrow"],
        captionVariants: ["Morning mobility in 60 seconds. No equipment needed. Save this for tomorrow morning."],
        blueprintData: {
          structurePattern: "hook-teach-expand-cta",
          units: [
            { id: "u-w1-1", order: 0, title: "Hook: Why your mornings feel stiff", role: "hook" },
            { id: "u-w1-2", order: 1, title: "Move 1: Cat-Cow (15s)", role: "value" },
            { id: "u-w1-3", order: 2, title: "Move 2: Thoracic rotation (15s)", role: "value" },
            { id: "u-w1-4", order: 3, title: "Move 3: Hip circles (15s)", role: "value" },
            { id: "u-w1-5", order: 4, title: "CTA: Follow for daily flows", role: "cta" },
          ],
          engagementDrivers: ["save", "follow"],
          primaryCTAType: "follow",
          formatCoherenceConfirmed: true,
          logicalProgressionConfirmed: true,
          accessibilityPlanConfirmed: true,
        },
      },
      assets: [
        { id: "a-w1-1", label: "Vertical video (9:16, 60s)", required: true, completed: true },
        { id: "a-w1-2", label: "Captions overlay (SRT)", required: true, completed: false },
        { id: "a-w1-3", label: "Cover still frame", required: false, completed: false },
        { id: "a-w1-4", label: "Music license evidence", required: true, completed: true },
        { id: "a-w1-5", label: "Talent release", required: true, completed: true },
      ],
      tasks: [
        { id: "t-w1-1", label: "Film flow sequence", assignee: "On-camera", completed: true },
        { id: "t-w1-2", label: "Edit with music", assignee: "Editor", completed: true },
        { id: "t-w1-3", label: "Add captions/text overlays", assignee: "Editor", completed: false },
        { id: "t-w1-4", label: "Select cover", assignee: "Designer", completed: false },
      ],
      versions: [
        { label: "Brief Approved", savedAt: "2026-02-22T10:00:00" },
        { label: "Draft v1 Complete", savedAt: "2026-02-23T15:00:00" },
        { label: "Blueprint Locked", savedAt: "2026-02-24T11:00:00" },
      ],
    },
  },

  // ─── Job 2: TikTok Video — Desk Neck Stretches ─── IN PRODUCTION (step: draft)
  {
    id: "w2",
    stage: "concept",
    status: "in-progress",
    title: "3 Yoga Stretches for Desk Neck (Quick demo)",
    description: "Fast-cut demonstration of three targeted stretches for neck and upper back tension caused by prolonged desk work. Subtitles required for accessibility.",
    pillarIds: ["p2"],
    segmentIds: ["s1", "s5"],
    createdAt: "2026-02-21T09:00:00",
    updatedAt: "2026-02-25T16:00:00",
    hook: "Your neck does this 8 hours a day. Here's the fix.",
    objective: "awareness",
    owner: "Brett Lewis",
    platform: "tiktok",
    contentType: "short-video",
    keyMessage: "Desk neck is reversible with 3 simple stretches",
    production: {
      productionStep: "draft",
      brief: {
        strategy: { objective: "awareness", audienceSegmentIds: ["s1", "s5"], pillarIds: ["p2"], keyMessage: "Desk neck is reversible with 3 simple stretches", ctaType: "none", tonePreset: "casual" },
        platformRules: { durationTarget: 30, hookType: "problem-first", creatorVoice: "casual" },
        creativePlan: {},
        compliance: { containsClaims: false, disclosureNeeded: false },
        approved: true, approvedAt: "2026-02-23T09:00:00", approvedBy: "Brand Reviewer",
      },
      sources: [],
      outputs: {},
      assets: [
        { id: "a-w2-1", label: "Vertical video (9:16)", required: true, completed: false },
        { id: "a-w2-2", label: "On-screen text overlays", required: true, completed: false },
        { id: "a-w2-3", label: "Talent release", required: true, completed: false },
      ],
      tasks: [],
      versions: [{ label: "Brief Approved", savedAt: "2026-02-23T09:00:00" }],
    },
  },

  // ─── Job 3: YouTube Long-form — Beginner Back Yoga ─── IN PRODUCTION (step: brief)
  {
    id: "w3",
    stage: "concept",
    status: "in-progress",
    title: "Beginner Yoga for Lower Back Relief (15 minutes)",
    description: "Full 15-minute guided yoga sequence for lower back discomfort. Includes safety disclaimer and claim substantiation for health benefits. Targets desk workers and beginners.",
    pillarIds: ["p2", "p3"],
    segmentIds: ["s4", "s5"],
    createdAt: "2026-02-18T08:00:00",
    updatedAt: "2026-02-26T09:00:00",
    hook: "Do you sit at a desk all day? This 15-minute flow could change everything.",
    objective: "trust",
    owner: "Brett Lewis",
    platform: "youtube",
    contentType: "long-form",
    keyMessage: "15 minutes of gentle yoga may help reduce lower back discomfort",
    claimsFlag: true,
    sourceLinks: ["https://pubmed.example.com/yoga-back-pain-study"],
    production: {
      productionStep: "brief",
      brief: {
        strategy: { objective: "trust", audienceSegmentIds: ["s4", "s5"], pillarIds: ["p2", "p3"], keyMessage: "15 minutes of gentle yoga may help reduce lower back discomfort", ctaType: "link", ctaText: "Free class signup in description", tonePreset: "empathetic" },
        platformRules: { targetLengthMin: 14, targetLengthMax: 18, videoStyle: "tutorial", hookType: "problem-first", seoKeyword: "beginner yoga lower back", viewerPromise: "Feel relief in 15 minutes" },
        creativePlan: { storyArc: "hook-promise-sections-recap-cta" },
        compliance: {
          containsClaims: true,
          claims: [
            { claim: "May help reduce lower back discomfort", citation: "https://pubmed.example.com/yoga-back-pain-study", cited: true },
            { claim: "Safety disclaimer: Consult your healthcare provider", citation: "Standard disclaimer", cited: true },
          ],
          disclosureNeeded: false,
        },
        approved: false,
      },
      sources: [{ id: "src-w3", url: "https://pubmed.example.com/yoga-back-pain-study", title: "Yoga for Chronic Low Back Pain -- Systematic Review", keyTakeaways: "Moderate evidence that yoga reduces pain and improves function in adults with chronic low back pain", type: "article" }],
      outputs: {},
      assets: [],
      tasks: [],
      versions: [],
    },
  },

  // ─── Job 4: LinkedIn Document — Wellness Microbreaks ─── IN PRODUCTION (step: blueprint)
  {
    id: "w4",
    stage: "concept",
    status: "in-progress",
    title: "Wellness at Work: 5 Microbreak Routines for Teams",
    description: "LinkedIn document carousel targeting HR and wellness professionals. Includes productivity data claims requiring source citations. Paid boosted for lead generation.",
    pillarIds: ["p2", "p4"],
    segmentIds: ["s2", "s5"],
    createdAt: "2026-02-19T10:00:00",
    updatedAt: "2026-02-27T08:00:00",
    hook: "Your team's productivity drops 40% after 90 minutes without a break.",
    objective: "leads",
    owner: "Brett Lewis",
    platform: "linkedin",
    contentType: "ln-document",
    keyMessage: "5 microbreak routines that boost team productivity and reduce strain",
    claimsFlag: true,
    production: {
      productionStep: "blueprint",
      brief: {
        strategy: { objective: "lead-gen", audienceSegmentIds: ["s2", "s5"], pillarIds: ["p2", "p4"], keyMessage: "5 microbreak routines that boost team productivity", ctaType: "link", ctaText: "Download the full playbook", tonePreset: "professional" },
        platformRules: { carouselGoal: "convert", slideCount: 9, hashtagStyle: "light" },
        creativePlan: {},
        compliance: {
          containsClaims: true,
          claims: [
            { claim: "Microbreaks improve productivity by 13%", citation: "https://example.com/productivity-study", cited: true },
            { claim: "Reduce musculoskeletal discomfort", citation: "https://example.com/ergonomics-research", cited: true },
          ],
          disclosureNeeded: true, disclosureType: "Paid promotion",
        },
        approved: true, approvedAt: "2026-02-24T14:00:00", approvedBy: "Brand Reviewer",
      },
      sources: [
        { id: "src-w4a", url: "https://example.com/productivity-study", title: "Microbreaks and Workplace Productivity", keyTakeaways: "13% productivity increase with regular microbreaks", type: "report" },
        { id: "src-w4b", url: "https://example.com/ergonomics-research", title: "Ergonomic Interventions for Office Workers", keyTakeaways: "Structured movement breaks reduce MSD risk", type: "article" },
      ],
      outputs: {
        captionVariants: ["Your team needs this. 5 microbreak routines backed by research. Download the full playbook (link in post)."],
      },
      assets: [
        { id: "a-w4-1", label: "PDF document (9 pages)", required: true, completed: false },
        { id: "a-w4-2", label: "Cover page design", required: true, completed: false },
        { id: "a-w4-3", label: "Claim substantiation docs", required: true, completed: true },
        { id: "a-w4-4", label: "Campaign brief / ad setup", required: true, completed: false },
      ],
      tasks: [],
      versions: [
        { label: "Brief Approved", savedAt: "2026-02-24T14:00:00" },
        { label: "Draft v1 Complete", savedAt: "2026-02-25T10:00:00" },
      ],
    },
  },

  // ─── Job 5: Facebook Link Post — Mediterranean Meal Prep ─── PUBLISHED
  {
    id: "w5",
    stage: "post",
    status: "published",
    title: "New Blog: Mediterranean Meal Prep for Busy Weeks",
    description: "Facebook link post driving traffic to a blog article about Mediterranean-style meal prep. Simple teaser copy with preview image and UTM tracking.",
    pillarIds: ["p2"],
    segmentIds: ["s4"],
    createdAt: "2026-02-10T11:00:00",
    updatedAt: "2026-02-20T12:00:00",
    hook: "Healthy eating shouldn't take your whole Sunday.",
    objective: "trust",
    owner: "Brett Lewis",
    platform: "facebook",
    contentType: "fb-link-post",
    keyMessage: "Mediterranean meal prep saves time and tastes amazing",
    caption: "Healthy eating doesn't have to take your whole Sunday. Our new guide breaks down a full week of Mediterranean-style meals in under 2 hours. Link in post.",
    metrics: { views: 4200, likes: 380, comments: 45, shares: 120, engagementRate: 5.2, reach: 12800 },
  },

  // ─── Job 6: Instagram Stories — Hydration Challenge ─── IN PRODUCTION (step: packaging)
  {
    id: "w6",
    stage: "concept",
    status: "in-progress",
    title: "7-Day Hydration Challenge (Day 1 prompt + poll)",
    description: "Instagram Stories series kicking off a 7-day hydration challenge. 4 frames with poll and question sticker to drive engagement and replies.",
    pillarIds: ["p2"],
    segmentIds: ["s4"],
    createdAt: "2026-02-22T08:00:00",
    updatedAt: "2026-02-26T17:00:00",
    hook: "Day 1: How many glasses of water have you had today?",
    objective: "engagement",
    owner: "Brett Lewis",
    platform: "instagram",
    contentType: "story",
    keyMessage: "Hydration is the easiest wellness habit to start",
    production: {
      productionStep: "packaging",
      brief: {
        strategy: { objective: "awareness", audienceSegmentIds: ["s4"], pillarIds: ["p2"], keyMessage: "Start your hydration habit today", ctaType: "comment", ctaText: "Vote: How many glasses today?", tonePreset: "playful" },
        platformRules: { frameCount: 4, interactionType: "poll" },
        creativePlan: {
          frames: [
            { id: "f1", frameNumber: 1, script: "Day 1: Your hydration challenge starts NOW", onScreenText: "Bold text + water emoji", stickerRecommendation: "None" },
            { id: "f2", frameNumber: 2, script: "Today's goal: 8 glasses", onScreenText: "Tracker graphic", stickerRecommendation: "Question: How many so far?" },
            { id: "f3", frameNumber: 3, script: "Quick tip: Add lemon or mint", onScreenText: "Tip text", stickerRecommendation: "None" },
            { id: "f4", frameNumber: 4, script: "Your turn!", onScreenText: "Poll prompt", stickerRecommendation: "Poll: Crushing it / Need help" },
          ],
        },
        compliance: { containsClaims: false, disclosureNeeded: false },
        approved: true, approvedAt: "2026-02-24T09:00:00", approvedBy: "Brand Reviewer",
      },
      sources: [],
      outputs: {},
      assets: [
        { id: "a-w6-1", label: "Story frames (1080x1920) x4", required: true, completed: true },
        { id: "a-w6-2", label: "Music license evidence", required: true, completed: true },
      ],
      tasks: [
        { id: "t-w6-1", label: "Design 4 story frames", assignee: "Designer", completed: true },
        { id: "t-w6-2", label: "Configure poll + question stickers", assignee: "Writer", completed: true },
        { id: "t-w6-3", label: "Final review", assignee: "Approver", completed: false },
      ],
      versions: [
        { label: "Brief Approved", savedAt: "2026-02-24T09:00:00" },
        { label: "Draft v1 Complete", savedAt: "2026-02-25T11:00:00" },
        { label: "Blueprint Locked", savedAt: "2026-02-25T14:00:00" },
        { label: "Assets Complete", savedAt: "2026-02-26T10:00:00" },
      ],
    },
  },

  // ─── Job 7: Facebook Live — Beginner Yoga + Q&A ─── CONCEPT (draft)
  {
    id: "w7",
    stage: "concept",
    status: "draft",
    title: "Live: 20-min Beginner Yoga + Q&A",
    description: "Facebook Live session featuring a 20-minute beginner yoga flow followed by live Q&A. Requires moderator assignment, run-of-show planning, and tech rehearsal checklist.",
    pillarIds: ["p2"],
    segmentIds: ["s4"],
    createdAt: "2026-02-23T10:00:00",
    updatedAt: "2026-02-25T11:00:00",
    hook: "Join us live for a beginner-friendly yoga flow. No experience needed.",
    objective: "engagement",
    owner: "Brett Lewis",
    platform: "facebook",
    contentType: "fb-live",
    keyMessage: "Yoga is for everyone -- join us live and ask questions in real time",
  },

  // ─── Job 8: YouTube Shorts — Downward Dog Fix ─── IN PRODUCTION (step: qa)
  {
    id: "w8",
    stage: "concept",
    status: "in-progress",
    title: "One Pose Fix: Downward Dog Alignment Tip",
    description: "YouTube Shorts tutorial correcting common Downward Dog mistakes. Strong opening hook with on-screen alignment cues and captions required for accessibility.",
    pillarIds: ["p2"],
    segmentIds: ["s4"],
    createdAt: "2026-02-21T14:00:00",
    updatedAt: "2026-02-27T09:00:00",
    hook: "You're doing Downward Dog wrong. Here's the fix.",
    objective: "awareness",
    owner: "Brett Lewis",
    platform: "youtube",
    contentType: "shorts",
    keyMessage: "One alignment fix transforms your Downward Dog",
    production: {
      productionStep: "qa",
      brief: {
        strategy: { objective: "awareness", audienceSegmentIds: ["s4"], pillarIds: ["p2"], keyMessage: "One alignment fix transforms your Downward Dog", ctaType: "subscribe", ctaText: "Subscribe for daily tips", tonePreset: "educational" },
        platformRules: { durationTarget: 45, hookType: "pattern-break" },
        creativePlan: {},
        compliance: { containsClaims: false, disclosureNeeded: false },
        approved: true, approvedAt: "2026-02-23T14:00:00", approvedBy: "Brand Reviewer",
      },
      sources: [],
      outputs: {
        scriptVersions: [{ id: "sv-w8", content: "0:00-0:03 Hook: You're doing this wrong.\n0:03-0:10 Common mistake: hands too close, hips not lifted\n0:10-0:30 The Fix: hands shoulder-width, push hips back, slight knee bend\n0:30-0:40 Before vs After comparison\n0:40-0:45 Subscribe for daily tips", version: 1, approved: true }],
        hookVariants: ["You're doing Downward Dog wrong", "This one fix changes everything", "Stop hurting your wrists in Down Dog", "Your yoga teacher should have told you this"],
      },
      assets: [
        { id: "a-w8-1", label: "Vertical video (9:16, <=60s)", required: true, completed: true },
        { id: "a-w8-2", label: "Captions overlay (burned)", required: true, completed: true },
        { id: "a-w8-3", label: "Cover still frame", required: false, completed: true },
        { id: "a-w8-4", label: "Talent release", required: true, completed: true },
      ],
      tasks: [
        { id: "t-w8-1", label: "Film pose demo", assignee: "On-camera", completed: true },
        { id: "t-w8-2", label: "Edit with alignment cues", assignee: "Editor", completed: true },
        { id: "t-w8-3", label: "Add captions", assignee: "Editor", completed: true },
        { id: "t-w8-4", label: "QA review", assignee: "Approver", completed: false },
      ],
      internalApproval: { approved: true, comments: ["Great demo, captions look clean"], reviewer: "Editor" },
      versions: [
        { label: "Brief Approved", savedAt: "2026-02-23T14:00:00" },
        { label: "Draft v1 Complete", savedAt: "2026-02-24T10:00:00" },
        { label: "Blueprint Locked", savedAt: "2026-02-24T16:00:00" },
        { label: "Assets Complete", savedAt: "2026-02-25T14:00:00" },
        { label: "Internal Approval", savedAt: "2026-02-26T10:00:00" },
      ],
    },
  },

  // ─── Job 9: LinkedIn Text Post — Founder Fitness Note ─── SCHEDULED
  {
    id: "w9",
    stage: "post",
    status: "scheduled",
    title: "Founder note: Building a sustainable fitness habit (3 lessons)",
    description: "LinkedIn text post from the founder's perspective sharing 3 lessons learned about building a sustainable fitness routine. First-person narrative with tight structure and recruiting CTA.",
    pillarIds: ["p5"],
    segmentIds: ["s2", "s5"],
    createdAt: "2026-02-20T07:00:00",
    updatedAt: "2026-02-26T15:00:00",
    hook: "I failed at fitness for 10 years. Then I changed one thing.",
    objective: "leads",
    owner: "Brett Lewis",
    platform: "linkedin",
    contentType: "ln-text-post",
    keyMessage: "Sustainable fitness starts with identity, not intensity",
    caption: "I failed at fitness for 10 years. Then I changed one thing.\n\nLesson 1: Start so small it feels silly.\nLesson 2: Tie it to something you already do.\nLesson 3: Track streaks, not reps.\n\nWe're building tools for people who want health without hustle culture. If that resonates -- we're hiring.\n\n#FitnessHabit #WellnessLeadership #Hiring",
    scheduledDate: "2026-03-01",
    scheduledTime: "07:30",
    reviewNotes: "Approved -- authentic tone, good CTA.",
    approvedBy: "Brett Lewis",
    approvedAt: "2026-02-26T15:00:00",
  },

  // ─── Job 10: TikTok Photo Carousel — Protein Snacks ─── IN PRODUCTION (step: blueprint)
  {
    id: "w10",
    stage: "concept",
    status: "in-progress",
    title: "Grocery List: High-Protein Snacks Under 200 Calories",
    description: "TikTok Photo Carousel listing high-protein snacks with verified calorie and protein data. Nutrition claims require USDA source citations. Designed for saves and shares.",
    pillarIds: ["p2"],
    segmentIds: ["s4"],
    createdAt: "2026-02-22T11:00:00",
    updatedAt: "2026-02-26T13:00:00",
    hook: "Save this grocery list. Every snack is under 200 calories and packed with protein.",
    objective: "engagement",
    owner: "Brett Lewis",
    platform: "tiktok",
    contentType: "photo-carousel",
    keyMessage: "High-protein snacking under 200 cal -- sourced and verified",
    claimsFlag: true,
    production: {
      productionStep: "blueprint",
      brief: {
        strategy: { objective: "awareness", audienceSegmentIds: ["s4"], pillarIds: ["p2"], keyMessage: "High-protein snacking under 200 cal", ctaType: "none", tonePreset: "casual" },
        platformRules: { carouselGoal: "teach", slideCount: 9, hashtagStyle: "heavy" },
        creativePlan: {},
        compliance: {
          containsClaims: true,
          claims: [
            { claim: "Each snack under 200 calories (USDA verified)", citation: "https://fdc.nal.usda.gov", cited: true },
            { claim: "High-protein (>=7g per serving)", citation: "https://fdc.nal.usda.gov", cited: true },
          ],
          disclosureNeeded: false,
        },
        approved: true, approvedAt: "2026-02-24T16:00:00", approvedBy: "Brand Reviewer",
      },
      sources: [{ id: "src-w10", url: "https://fdc.nal.usda.gov", title: "USDA FoodData Central", keyTakeaways: "Verified calorie and macronutrient data for all listed snacks", type: "docs" }],
      outputs: {
        captionVariants: ["Save this for your next grocery run. Every snack: under 200 cal, high protein, actually tastes good."],
      },
      assets: [
        { id: "a-w10-1", label: "Slide images (9:16) x9", required: true, completed: false },
        { id: "a-w10-2", label: "Cover image", required: true, completed: false },
        { id: "a-w10-3", label: "Claim substantiation (USDA)", required: true, completed: true },
      ],
      tasks: [],
      versions: [
        { label: "Brief Approved", savedAt: "2026-02-24T16:00:00" },
        { label: "Draft v1 Complete", savedAt: "2026-02-25T09:00:00" },
      ],
    },
  },

  // ─── Job 11: Instagram Reels — Partner Collab ─── CONCEPT (draft, needs setup)
  {
    id: "w11",
    stage: "concept",
    status: "draft",
    title: "Collab Reel: Post-Workout Stretch Routine with @CreatorName",
    description: "Partnered Instagram Reel with a fitness creator. Requires paid partnership disclosure, partner tagging, agreed posting date, and dual talent releases.",
    pillarIds: ["p2", "p5"],
    segmentIds: ["s4"],
    createdAt: "2026-02-24T09:00:00",
    updatedAt: "2026-02-26T11:00:00",
    hook: "What does @CreatorName do after every workout? This 5-move cooldown.",
    objective: "awareness",
    owner: "Brett Lewis",
    platform: "instagram",
    contentType: "reel",
    keyMessage: "Post-workout stretching is non-negotiable -- here's a pro's routine",
  },

  // ─── Job 12: TikTok Paid Ad — Yoga Reset ─── CONCEPT (draft, needs campaign setup)
  {
    id: "w12",
    stage: "concept",
    status: "draft",
    title: "Ad: Free 7-Day Yoga Reset -- Email Signup",
    description: "TikTok paid conversion ad driving email signups for a free 7-day yoga challenge. Requires campaign setup, destination URL, ad disclaimer, and claim substantiation.",
    pillarIds: ["p4"],
    segmentIds: ["s4"],
    createdAt: "2026-02-25T10:00:00",
    updatedAt: "2026-02-27T08:00:00",
    hook: "Feeling stiff? This free 7-day yoga reset will change how your body feels.",
    objective: "conversion",
    owner: "Brett Lewis",
    platform: "tiktok",
    contentType: "short-video",
    keyMessage: "Start your free 7-day yoga reset -- feel better by next week",
    claimsFlag: true,
  },
];
